<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LT075305" name="OCTS_USECASE_Employee.HCM_AssignedPayroll_Webservice_MainClass" tests="1" failures="0" timestamp="21 Sep 2018 07:27:21 GMT" time="1.704" errors="1">
  <testcase name="HCM_AssignedPayroll" time="1.704" classname="OCTS_USECASE_Employee.HCM_AssignedPayroll_Webservice_MainClass">
    <error type="java.lang.Exception" message="UploadFileToUcm: Error occurred while sending SOAP Request to Server">
      <![CDATA[java.lang.Exception: UploadFileToUcm: Error occurred while sending SOAP Request to Server
at OCTS_USECASE_Employee.HCM_AssignedPayroll_Webservice_MainClass.HCM_AssignedPayroll(HCM_AssignedPayroll_Webservice_MainClass.java:389)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at OCTS_Automation_Main_Modules.Invoke_TestNG_Classes.iterateThroughTestCases(Invoke_TestNG_Classes.java:171)
at OCTS_UI.FXMLController$1.call(FXMLController.java:580)
at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- HCM_AssignedPayroll -->
</testsuite> <!-- OCTS_USECASE_Employee.HCM_AssignedPayroll_Webservice_MainClass -->
