<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LT075305" ignored="0" name="test-number-25" tests="1" failures="1" timestamp="21 Sep 2018 03:35:51 GMT" time="540.102" errors="0">
  <testcase name="HCM_PersonAbsence" time="540.089" classname="OCTS_USECASE_Employee.HCM_PersonAbsence_Webservice_MainClass">
    <failure type="java.lang.Exception" message="Error: Job not loaded successfully.Please check the error in the application">
      <![CDATA[java.lang.Exception: Error: Job not loaded successfully.Please check the error in the application
at OCTS_USECASE_Employee.HCM_PersonAbsence_Webservice_MainClass.HCM_PersonAbsence(HCM_PersonAbsence_Webservice_MainClass.java:456)
at OCTS_Automation_Main_Modules.Invoke_TestNG_Classes.iterateThroughTestCases(Invoke_TestNG_Classes.java:171)
at OCTS_UI.FXMLController$1.call(FXMLController.java:580)
at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- HCM_PersonAbsence -->
</testsuite> <!-- test-number-25 -->
